import Head from 'next/head'
import Image from 'next/image'
import { IM_Fell_English, Inter } from '@next/font/google'
import Navbar from '@/Components/Navbar'
import Footer from '@/Components/Footer'
import { HomePage } from '@/Components/Homepage'
import { Typing } from './Typing'
import { English } from './English'
import { Ui } from './ui'
import { Frontend } from './Frontend'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <HomePage/> */}
        {/* <Typing/> */}
        {/* <English/> */}
        {/* <Ui/> */}
        <Frontend/>

      </main>

    </>
  )
}
